FROM node:12

WORKDIR /usr/src/app
COPY . .

WORKDIR /usr/src/app/settings-service-ui
RUN npm install
RUN npm run build

WORKDIR /usr/src/app

RUN npm install

EXPOSE 8000

CMD [ "node", "server.js" ]